services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: pricing_calculator
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - sabatini-network
  calculadora-precificacao-pc:
    image: lucassabatini/calculadora_precificacao
    restart: always
    working_dir: /CalculadoraPrecificacaoPC
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/pricing_calculator
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin
    ports:
        - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
        - sabatini-network
networks:
  sabatini-network:
    driver: bridge